language: node_js

node_js:
  - "lts/*"

os:
  - linux
  - windows

services:
  - docker

cache:
  directories:
    - "node_modules"

before_script:
  - if [[ "$TRAVIS_OS_NAME" != 'windows' ]]; then npm run docker:regtest && npm run docker:ganache; fi
  - if [[ "$TRAVIS_OS_NAME" != 'windows' ]]; then sleep 20 && npm run docker:ganache:deploy; fi

script:
  - npm run compile
  - npm run lint
  - npm run test:unit
  - if [[ "$TRAVIS_OS_NAME" != 'windows' ]]; then npm run test:int; fi
